-- S&S Group · Control de Cuentas
-- Ejecutar en Supabase > SQL Editor > New query

create table if not exists clientes (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  cuit text,
  modalidad text not null default 'Factura',
  honorario numeric(14,2) default 0,
  vigente_desde date,
  dia_generacion integer default 1,
  activo boolean default true,
  observaciones text
);

create table if not exists honorarios (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id) on delete cascade,
  vigente_desde date not null,
  honorario numeric(14,2) not null,
  nota text
);

create table if not exists movimientos (
  id bigint generated by default as identity primary key,
  fecha date not null,
  cliente_id bigint not null references clientes(id) on delete cascade,
  tipo text not null,
  descripcion text,
  importe numeric(14,2) not null,
  periodo date,
  comprobante text,
  pdf_path text,
  estado_conciliacion text,
  creado_en timestamptz not null default now()
);

create unique index if not exists ux_movimientos_unico
on movimientos(cliente_id, tipo, periodo, comprobante)
where comprobante is not null;

-- Bucket privado para guardar facturas PDF.
insert into storage.buckets (id, name, public)
values ('facturas','facturas',false)
on conflict (id) do nothing;
